# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('halfbaths', models.IntegerField()),
                ('square_meters', models.FloatField()),
                ('floors', models.IntegerField()),
                ('basements', models.IntegerField()),
                ('garage', models.CharField(choices=[('0', 'No garage'), ('1', '1-car garage'), ('2', '2-car garage'), ('3', '2+ car garage')], max_length=1)),
                ('parking', models.CharField(max_length=100)),
                ('extras', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_meters', models.FloatField()),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_meters', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
                ('description', models.TextField()),
                ('zoning', models.CharField(default='residential', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('published', models.BooleanField(default=False)),
                ('publish_date', models.DateField(verbose_name='date published')),
                ('edit_date', models.DateField(verbose_name='latest edit')),
                ('status', models.CharField(choices=[('S', 'Sold'), ('A', 'Available'), ('R', 'Removed'), ('P', 'Pending Sale')], max_length=1)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('property_tax', models.FloatField()),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('property_type', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('CAN', 'Canada')], max_length=100)),
                ('province', models.CharField(choices=[('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('ON', 'Ontario'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('AB', 'Alberta'), ('BC', 'British Columbia'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut')], max_length=2)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('community', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=6)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_meters', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('description', models.TextField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Lot')),
            ],
        ),
        migrations.CreateModel(
            name='SuiteRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_meters', models.FloatField()),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('house_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.House')),
                ('unit_number', models.CharField(max_length=10)),
                ('annual_strata_fee', models.FloatField()),
                ('pet_rules', models.CharField(max_length=100)),
                ('shared_fitness_room', models.BooleanField(default=False)),
                ('shared_pool', models.BooleanField(default=False)),
                ('shared_party_room', models.BooleanField(default=False)),
                ('shared_private_courtyard', models.BooleanField(default=False)),
                ('shared_laundry', models.BooleanField(default=False)),
                ('units_in_building', models.IntegerField()),
                ('building_floors', models.IntegerField()),
            ],
            bases=('property.house',),
        ),
        migrations.AddField(
            model_name='lot',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
        migrations.AddField(
            model_name='houseroom',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.House'),
        ),
        migrations.AddField(
            model_name='house',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
        migrations.AddField(
            model_name='suiteroom',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Suite'),
        ),
    ]
