# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('login_email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('b_email', models.BooleanField(default=True)),
                ('b_phone', models.BooleanField(default=False)),
                ('b_fax', models.BooleanField(default=False)),
                ('b_mail', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.User'),
        ),
    ]
