# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='creation_stamp',
            field=models.DateTimeField(verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='property',
            name='publish_stamp',
            field=models.DateTimeField(default=None, null=True, verbose_name='publish time'),
        ),
    ]
