# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20171127_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default='2017-11-27 15:35+00:00', verbose_name='Last Login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='b_email',
            field=models.BooleanField(default=True, verbose_name='Show email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='b_fax',
            field=models.BooleanField(default=False, verbose_name='Show fax'),
        ),
        migrations.AlterField(
            model_name='user',
            name='b_mail',
            field=models.BooleanField(default=False, verbose_name='Show mailing address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='b_phone',
            field=models.BooleanField(default=False, verbose_name='Show phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default='default@example.com', max_length=100, verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fax number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='login_email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Mailing address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
