# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20171124_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='length',
            new_name='depth',
        ),
    ]
