# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20171128_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='extras',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='suite',
            name='extras',
            field=models.TextField(blank=True),
        ),
    ]
