# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20171130_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('U', 'Unpublished'), ('S', 'Sold'), ('A', 'Listed'), ('R', 'Removed'), ('P', 'Pending Sale')], max_length=1),
        ),
    ]
